Tailwindcss
KiveshVirasamy/flight-tracker pull request #4
Opened 2023-02-26 10:40 UTC by KiveshVirasamy

Please see where I am going wrong this is not working its supposed too.

2023-02-26 11:15 UTC, CharelMarais requested changes
Please check the comments on the needed adjustments.

2023-02-26 11:15 UTC, CharelMarais commented on tailwind.config.cjs
> +  content: ["./src/**/*.{html,js,ts}"],
content: ["./src/**/*.{html,js,ts}", "./index.html" ] to allow tailwind to use the tailwind in your HTML file

2023-02-26 11:15 UTC, CharelMarais commented on index.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.17/tailwind.min.css">
You do not need line 10 if you adjust the tailwind config file.

2023-03-05 17:39 UTC, JonathanLadwig commented
I don't see any problems. You're good to merge.

2023-03-05 17:40 UTC, JonathanLadwig approved these changes
Rest Easy My Son

2023-03-05 17:41 UTC, JonathanLadwig commented
Just fix your merge conflicts

2023-03-05 17:41 UTC, merged